DBLab/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('app.urls')),
    url(r'^admin/', admin.site.urls),
]

app/urls.py
from django.conf.urls import url

from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^(?P<username>\w{0,50})/$', views.home, name='home'),
    url(r'^get/project/(?P<id>\d+)/$', views.getProject, name='get_project'),
    url(r'^question/ask/$', views.askQuestion, name='ask_question'),
    url(r'^problem/(?P<id>\d+)/$', views.showQuestion, name='show_problem'),
    url(r'^answer/correctness/(?P<question_id>\d+)/(?P<answer_id>\d+)/(?P<user_id>\d+)/(?P<is_correct>\d+)/$', views.answerCorrectness, name='answer_correctness'),
    url(r'^make/project/$', views.makePorject, name='make_project'),
    url(r'^make/quiz/$', views.makeQuiz, name='make_quiz'),
    url(r'^make/quiz/question/(?P<quiz_id>\d+)/$', views.makeQuizQuestion, name='make_quiz_question'),
    url(r'^make/quiz/question/choice/(?P<quiz_id>\d+)/(?P<quiz_question_id>\d+)/$', views.makeQuizQuestionChoice, name='make_quiz_question_choice'),
    url(r'^quiz/(?P<quiz_id>\d+)/$', views.showQuiz, name='show_quiz'),

]

app/templates/app/user/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'app/css/common.css' %}">
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="#">Home</a></li>
        <li><a href="#">Profile</a></li>
        {% if user.role == "admin" %}
          <li><a class="btn" data-toggle="modal" data-target="#makeProjectModel">Make Project</a></li>
          <li><a class="btn" data-toggle="modal" data-target="#makeQuizModel">Make Quiz</a></li>
        {% endif %}
        <li><a>User Score: {{ user.score }}</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a class="btn" data-toggle="modal" data-target="#askQuestionModel"><span class="glyphicon glyphicon-question-sign" style="margin-right: 5px;"></span>Ask Question</a></li>
        <li><a href="{% url 'app:logout' %}"><span class="glyphicon glyphicon-log-out" style="margin-right: 5px;"></span>Logout</a></li>
      </ul>
    </div>
  </div>
</nav>

<!-- Ask Question  Modal -->
<div id="askQuestionModel" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Ask question</h4>
      </div>
      <div class="modal-body">
         <form class="form-horizontal" action="{% url 'app:ask_question' %}" method="POST">
            <div class="form-group">
              <label class="control-label col-sm-2" for="title">Title:</label>
              <div class="col-sm-10">
                <input type="text" name="title" class="form-control" id="title" placeholder="Enter title..." required>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-2" for="description">Description:</label>
              <div class="col-sm-10">
                <textarea name="description" rows="8" id="description" placeholder="  Enter description..." required></textarea>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-10 col-sm-2">
                <button type="submit" class="btn btn-custom">Ask</button>
              </div>
            </div>
            {% csrf_token %}
          </form>
      </div>
    </div>
  </div>
</div>


<!-- Make Project  Modal -->
<div id="makeProjectModel" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Make project</h4>
      </div>
      <div class="modal-body">
         <form class="form-horizontal" action="{% url 'app:make_project' %}" method="POST">
            <div class="form-group">
              <label class="control-label col-sm-2" for="project_itle">Title:</label>
              <div class="col-sm-10">
                <input type="text" name="title" class="form-control" id="project_title" placeholder="Enter title..." required>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-2" for="project_description">Description:</label>
              <div class="col-sm-10">
                <textarea name="description" rows="8" id="project_description" placeholder="  Enter description..." required></textarea>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-2" for="score">Score:</label>
              <div class="col-sm-10">
                <input type="number" name="score" class="form-control" id="score" placeholder="Enter score..." required>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-2" for="min_score">Min socre:</label>
              <div class="col-sm-10">
                <input type="number" name="min_score" class="form-control" id="min_score" placeholder="Enter min socre..." required>
            </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-10 col-sm-2">
                <button type="submit" class="btn btn-custom">Submit</button>
              </div>
            </div>
            {% csrf_token %}
          </form>
      </div>
    </div>
  </div>
</div>


<!-- Make Quiz  Modal -->
<div id="makeQuizModel" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Make quiz</h4>
      </div>
      <div class="modal-body">
         <form class="form-horizontal" action="{% url 'app:make_quiz' %}" method="POST">
            <div class="form-group">
              <label class="control-label col-sm-2" for="quiz_title">Title:</label>
              <div class="col-sm-10">
                <input type="text" name="title" class="form-control" id="quiz_title" placeholder="Enter title..." required>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-10 col-sm-2">
                <button type="submit" class="btn btn-custom">Submit</button>
              </div>
            </div>
            {% csrf_token %}
          </form>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <h2>Quizes</h2>
      <div class="list-group">
      {% for quiz in quizes %}
        <a href="{% url 'app:show_quiz' quiz.id %}" class="list-group-item">
          <h4 class="list-group-item-heading">{{ quiz.title }}</h4>
        </a>
      {% endfor%}
      </div>
    </div>
    <div class="col-sm-8">
      <h2 style="margin-bottom: 20px;">Q&A</h2>
      {% for question in questions %}
      <div class="panel panel-default text-left">
        <div class="panel-heading">
          <span class="panel-title">Title: {{ question.title }}</span>
          <span class="pull-right">Asked by: {{ question.user.username }}</span>
        </div>
        <div class="panel-body">
          {{ question.description | truncatewords:100 }}
          <br>
          <a href="{% url 'app:show_problem' question.id %}" class="btn btn-custom pull-right">Show more</a>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="col-sm-2 sidenav projects text-left">
      <h2 class="text-center">Projects</h2>
      {% for project in projects %}
        <blockquote class="blockquote">
          <h4>Title: {{ project.title }}</h4>
          <p>Description: {{ project.description | truncatewords:10 }}</p>
          <p>Min score: {{ project.min_score }}</p>
          <p>Score: {{ project.score }}</p>
          <a href="{% url 'app:get_project' project.id %}" class="btn btn-custom">Get project</a>
        </blockquote>
      {% endfor %}
    </div>
    </div>
  </div>
  <script src="{% static 'app/js/jquery.min.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
</body>
</html>

app/templates/app/user/show_problem.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{ question.title }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'app/css/common.css' %}">
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'app:home' user.username %}">Home</a></li>
          <li><a href="#">Profile</a></li>
          {% if user.role == "admin" %}
            <li><a class="btn" data-toggle="modal" data-target="#makeProjectModel">Make Project</a></li>
            <li><a class="btn" data-toggle="modal" data-target="#makeQuizModel">Make Quiz</a></li>
          {% endif %}
          <li><a>User Score: {{ user.score }}</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a class="btn" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-question-sign" style="margin-right: 5px;"></span>Ask Question</a></li>
          <li><a href="{% url 'app:logout' %}"><span class="glyphicon glyphicon-log-out" style="margin-right: 5px;"></span>Logout</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Ask Question  Modal -->
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Ask a question</h4>
        </div>
        <div class="modal-body">
           <form class="form-horizontal" action="{% url 'app:ask_question' %}" method="POST">
              <div class="form-group">
                <label class="control-label col-sm-2" for="title">Title:</label>
                <div class="col-sm-10">
                  <input type="text" name="title" class="form-control" id="title" placeholder="Enter title..." required>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2" for="description">Description:</label>
                <div class="col-sm-10">
                  <textarea name="description" rows="8" id="description" placeholder="  Enter description..." required></textarea>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-10 col-sm-2">
                  <button type="submit" class="btn btn-custom">Ask</button>
                </div>
              </div>
              {% csrf_token %}
            </form>
        </div>
      </div>
    </div>
  </div>

<!-- Make Project  Modal -->
<div id="makeProjectModel" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Make project</h4>
      </div>
      <div class="modal-body">
         <form class="form-horizontal" action="{% url 'app:make_project' %}" method="POST">
            <div class="form-group">
              <label class="control-label col-sm-2" for="project_itle">Title:</label>
              <div class="col-sm-10">
                <input type="text" name="title" class="form-control" id="project_title" placeholder="Enter title..." required>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-2" for="project_description">Description:</label>
              <div class="col-sm-10">
                <textarea name="description" rows="8" id="project_description" placeholder="  Enter description..." required></textarea>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-2" for="score">Score:</label>
              <div class="col-sm-10">
                <input type="number" name="score" class="form-control" id="score" placeholder="Enter score..." required>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-2" for="min_score">Min score:</label>
              <div class="col-sm-10">
                <input type="number" name="min_score" class="form-control" id="min_score" placeholder="Enter min socre..." required>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-10 col-sm-2">
                <button type="submit" class="btn btn-custom">Submit</button>
              </div>
            </div>
            {% csrf_token %}
          </form>
      </div>
    </div>
  </div>
</div>


<!-- Make Quiz  Modal -->
<div id="makeQuizModel" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Make quiz</h4>
      </div>
      <div class="modal-body">
         <form class="form-horizontal" action="{% url 'app:make_quiz' %}" method="POST">
            <div class="form-group">
              <label class="control-label col-sm-2" for="quiz_title">Title:</label>
              <div class="col-sm-10">
                <input type="text" name="title" class="form-control" id="quiz_title" placeholder="Enter title..." required>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-10 col-sm-2">
                <button type="submit" class="btn btn-custom">Submit</button>
              </div>
            </div>
            {% csrf_token %}
          </form>
      </div>
    </div>
  </div>
</div>

  <div class="container-fluid text-center">
    <div class="row content">
      <div class="col-sm-2 sidenav">
        <h2>Quizes</h2>
        <div class="list-group">
        {% for quiz in quizes %}
          <a href="{% url 'app:show_quiz' quiz.id %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ quiz.title }}</h4>
          </a>
        {% endfor%}
        </div>
      </div>
      <div class="col-sm-8" style="margin-top: 72px;">
        <div class="panel panel-default text-left">
          <div class="panel-heading">
            <span class="panel-title">Title: {{ question.title }}</span>
            <span class="pull-right">Asked by: {{ question.user.username }}</span>
          </div>
          <div class="panel-body">
            {{ question.description }}
            <br>
          </div>
        </div>
        {% if answers %}
          {% for answer in answers %}
            <div class="panel panel-default text-left">
              <div class="panel-heading">
                <span class="panel-title">Answerd by: {{ answer.user.username }}</span>
              </div>
              <div class="panel-body">
                {{ answer.description }}
                <br>
              </div>
              {% if answer.user != user and not answer.status and question.user == user%}
              <div class="panel-footer" style="background-color: white;">
                <a href="{% url 'app:answer_correctness' answer_id=answer.id user_id=question.user.id is_correct=1  question_id=question.id %}" class="pull-right btn btn-success">Right</a>
                <a href="{% url 'app:answer_correctness' answer_id=answer.id user_id=question.user.id is_correct=0 question_id=question.id %}" class="pull-right btn btn-danger" style="margin-right: 3px;">Wrong</a>
                <div class="clearfix"></div>
              </div>
              {% endif %}
            </div>
          {% endfor %}
        {% endif%}
        <div class="row" style="margin-top: 50px;">
          <div class="col-md-12">
            <div class="well well-sm">
              <form class="form-horizontal" action="{% url 'app:show_problem' question.id %}" method="post">
              <fieldset>
                <legend class="text-center">Answer this </legend>
                <div class="form-group">
                  <label class="col-md-3 control-label" for="answer">Your answer</label>
                  <div class="col-md-9">
                    <textarea class="form-control" id="answer" name="description" placeholder="Please enter your answer here..." rows="5" required></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-12 text-right">
                    <button type="submit" class="btn btn-custom">Reply</button>
                  </div>
                </div>
              </fieldset>
              {% csrf_token %}
              </form>
            </div>
          </div>
      </div>
      </div>
      <div class="col-sm-2 sidenav projects text-left">
        <h2 class="text-center">Projects</h2>
        {% for project in projects %}
          <blockquote class="blockquote">
            <h4>Title: {{ project.title }}</h4>
            <p>Description: {{ project.description | truncatewords:10 }}</p>
            <p>Min score: {{ project.min_score }}</p>
            <p>Score: {{ project.score }}</p>
            <a href="{% url 'app:get_project' project.id %}" class="btn btn-custom">Get project</a>
          </blockquote>
        {% endfor %}
      </div>
    </div>
  </div>

  <script src="{% static 'app/js/jquery.min.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
</body>
</html>

app/templates/app/user/show_quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{ question.title }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'app/css/common.css' %}">
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'app:home' user.username %}">Home</a></li>
          <li><a href="#">Profile</a></li>
          {% if user.role == "admin" %}
            <li><a class="btn" data-toggle="modal" data-target="#makeProjectModel">Make Project</a></li>
            <li><a class="btn" data-toggle="modal" data-target="#makeQuizModel">Make Quiz</a></li>
          {% endif %}
          <li><a>User Score: {{ user.score }}</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a class="btn" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-question-sign" style="margin-right: 5px;"></span>Ask Question</a></li>
          <li><a href="{% url 'app:logout' %}"><span class="glyphicon glyphicon-log-out" style="margin-right: 5px;"></span>Logout</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Ask Question  Modal -->
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Ask a question</h4>
        </div>
        <div class="modal-body">
           <form class="form-horizontal" action="{% url 'app:ask_question' %}" method="POST">
              <div class="form-group">
                <label class="control-label col-sm-2" for="title">Title:</label>
                <div class="col-sm-10">
                  <input type="text" name="title" class="form-control" id="title" placeholder="Enter title..." required>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2" for="description">Description:</label>
                <div class="col-sm-10">
                  <textarea name="description" rows="8" id="description" placeholder="  Enter description..." required></textarea>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-10 col-sm-2">
                  <button type="submit" class="btn btn-custom">Ask</button>
                </div>
              </div>
              {% csrf_token %}
            </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Make Project  Modal -->
  <div id="makeProjectModel" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Make project</h4>
        </div>
        <div class="modal-body">
           <form class="form-horizontal" action="{% url 'app:make_project' %}" method="POST">
              <div class="form-group">
                <label class="control-label col-sm-2" for="project_itle">Title:</label>
                <div class="col-sm-10">
                  <input type="text" name="title" class="form-control" id="project_title" placeholder="Enter title..." required>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2" for="project_description">Description:</label>
                <div class="col-sm-10">
                  <textarea name="description" rows="8" id="project_description" placeholder="  Enter description..." required></textarea>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2" for="score">Score:</label>
                <div class="col-sm-10">
                  <input type="number" name="score" class="form-control" id="score" placeholder="Enter score..." required>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2" for="min_score">Min score:</label>
                <div class="col-sm-10">
                  <input type="number" name="min_score" class="form-control" id="min_score" placeholder="Enter min socre..." required>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-10 col-sm-2">
                  <button type="submit" class="btn btn-custom">Submit</button>
                </div>
              </div>
              {% csrf_token %}
            </form>
        </div>
      </div>
    </div>
  </div>


  <!-- Make Quiz  Modal -->
  <div id="makeQuizModel" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Make quiz</h4>
        </div>
        <div class="modal-body">
           <form class="form-horizontal" action="{% url 'app:make_quiz' %}" method="POST">
              <div class="form-group">
                <label class="control-label col-sm-2" for="quiz_title">Title:</label>
                <div class="col-sm-10">
                  <input type="text" name="title" class="form-control" id="quiz_title" placeholder="Enter title..." required>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-10 col-sm-2">
                  <button type="submit" class="btn btn-custom">Submit</button>
                </div>
              </div>
              {% csrf_token %}
            </form>
        </div>
      </div>
    </div>
  </div>


  <div class="container-fluid text-center">
    <div class="row content">
      <div class="col-sm-2 sidenav">
        <h2>Quizes</h2>
        <div class="list-group">
        {% for quiz in quizes %}
          <a href="{% url 'app:show_quiz' quiz.id %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ quiz.title }}</h4>
          </a>
        {% endfor%}
        </div>
      </div>
      <div class="col-sm-8">
        <h1>{{ quiz.title }}</h1>
        <form action="{% url 'app:show_quiz' quiz.id %}" method="POST">
        {% for question in questions %}
        <div class="panel panel-default text-left">
          <div class="panel-heading">
            <span class="panel-title">Title: {{ question.title }}</span>
            <span class="pull-right">Score: {{ question.score }}</span>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <p>{{ question.description }}</p>
              <br><br>
              {% for choice in question.choices %}
              {% with y=choice.id|stringformat:"s" %}
                <label class="radio-inline"><input type="radio" name="{{ forloop.parentloop.counter }}" value="{{ question.id|stringformat:'i'|add:'-'|add:y }}">{{ choice.text }}</label>
              {% endwith %}
              {% endfor %}
            </div>
          </div>
        </div>
        {% endfor %}
        <button type="submit" name="submit" class="btn btn-custom btn-lg">Submit</button>
        {% csrf_token %}
      </form>
      <br>
      </div>
      <div class="col-sm-2 sidenav projects text-left">
        <h2 class="text-center">Projects</h2>
        {% for project in projects %}
          <blockquote class="blockquote">
            <h4>Title: {{ project.title }}</h4>
            <p>Description: {{ project.description | truncatewords:10 }}</p>
            <p>Min score: {{ project.min_score }}</p>
            <p>Score: {{ project.score }}</p>
            <a href="{% url 'app:get_project' project.id %}" class="btn btn-custom">Get project</a>
          </blockquote>
        {% endfor %}
      </div>
    </div>
  </div>


  <script src="{% static 'app/js/jquery.min.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
</body>
</html>